metadata:
  uptime_in_hours:
    units: hours
    larger_is_better: 1
    precision: 2
    label: Uptime
  used_memory_in_mb:
    units: MB
    larger_is_better: 0
    precision: 0
    label: Used Memory
  connections_per_sec:
    units: conn/sec
    larger_is_better: 0
    precision: 2
    label: Connections
  commands_per_sec:
    units: com/sec
    larger_is_better: 0
    precision: 2
    label: Commands
  hits_per_sec:
    units: /sec
    larger_is_better: 1
    precision: 2
    label: Hits
  hits_ratio:
    label: Hits Ratio
  misses_per_sec:
    units: /sec
    larger_is_better: 0
    precision: 2
    label: Misses
  changes_since_last_save:
    larger_is_better: 0
    precision: 0
  connected_clients:
    larger_is_better: 0
    precision: 0
  connected_slaves:
    larger_is_better: 0
    precision: 0
  bgsave_in_progress:
    larger_is_better: 0
    precision: 0
    label: Background Save in Progress?
  up:
    label: up?
    precision: 0

triggers:
  - type: peak
    dname: up
    low_value: 0
  - type: plateau
    low_value: 0
    dname: master_link_status
    duration: 30
